# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  awl = {
    pname = "awl";
    version = "v0.19.0";
    src = fetchFromGitHub {
      owner = "anywherelan";
      repo = "awl";
      rev = "v0.19.0";
      fetchSubmodules = false;
      sha256 = "sha256-Tg442iFLxGgqQfXHiKeHMX4Y7IAIi63wYdrD5TLlN3E=";
    };
  };
  awl-flutter = {
    pname = "awl-flutter";
    version = "v0.19.0";
    src = fetchFromGitHub {
      owner = "anywherelan";
      repo = "awl-flutter";
      rev = "v0.19.0";
      fetchSubmodules = false;
      sha256 = "sha256-zSKCM3OczzShOrBv14qVzbKueezbsvsNq+5bJ+NcVLQ=";
    };
  };
  gitpane = {
    pname = "gitpane";
    version = "v0.14.1";
    src = fetchFromGitHub {
      owner = "affromero";
      repo = "gitpane";
      rev = "v0.14.1";
      fetchSubmodules = false;
      sha256 = "sha256-MDn6SVIaOkctDWrAlPj5lysXWzzQQDMNOtC7fxG/bYU=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-MDn6SVIaOkctDWrAlPj5lysXWzzQQDMNOtC7fxG_bYU=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  hammerspoon = {
    pname = "hammerspoon";
    version = "1.1.1";
    src = fetchurl {
      url = "https://github.com/Hammerspoon/hammerspoon/releases/download/1.1.1/Hammerspoon-1.1.1.zip";
      sha256 = "sha256-EbsckPr1Qn83x71P5+q5d0rkPh1csCDFswiNrDKEnvo=";
    };
  };
  omniwm = {
    pname = "omniwm";
    version = "v0.6.3";
    src = fetchurl {
      url = "https://github.com/BarutSRB/OmniWM/releases/download/v0.6.3/OmniWM-v0.6.3.zip";
      sha256 = "sha256-rDRDQYOUxvntH5mA1EoXa6LPeqV2zN3OpnaD+eHOLiU=";
    };
  };
  paperwm-spoon = {
    pname = "paperwm-spoon";
    version = "cb6dd31a392a0d79ed090befc03f05d0ad375bba";
    src = fetchFromGitHub {
      owner = "mogenson";
      repo = "PaperWM.spoon";
      rev = "cb6dd31a392a0d79ed090befc03f05d0ad375bba";
      fetchSubmodules = false;
      sha256 = "sha256-tbz2MJQZogdh643kMvfUI9XMTBhC2Mzd//nHChShkMQ=";
    };
    date = "2026-08-18";
  };
  pokepet = {
    pname = "pokepet";
    version = "5b60c32341552bf2faa2da0a69fb7b2583019c66";
    src = fetchFromGitHub {
      owner = "n-parisi";
      repo = "pokepet";
      rev = "5b60c32341552bf2faa2da0a69fb7b2583019c66";
      fetchSubmodules = false;
      sha256 = "sha256-zis+b2rjcFPlC5Wn1LnOwYcSMO1RiY1KXsGSSM0fDyc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-zis+b2rjcFPlC5Wn1LnOwYcSMO1RiY1KXsGSSM0fDyc=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-08-24";
  };
  powershell-beautifier = {
    pname = "powershell-beautifier";
    version = "V1.2.5";
    src = fetchFromGitHub {
      owner = "DTW-DanWard";
      repo = "PowerShell-Beautifier";
      rev = "V1.2.5";
      fetchSubmodules = false;
      sha256 = "sha256-N/Wz2TDgQFEW//QR5SwzFFJAiRx8+RoMS842m27mYjM=";
    };
  };
  vpet = {
    pname = "vpet";
    version = "v1.0";
    src = fetchFromGitHub {
      owner = "jonaustin";
      repo = "vpet";
      rev = "v1.0";
      fetchSubmodules = false;
      sha256 = "sha256-QvDqa4rM+k0Eb9nwvVUxv4hAAX6jkwEuCUWud7azAug=";
    };
  };
}
