# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  gitpane = {
    pname = "gitpane";
    version = "v0.9.1";
    src = fetchFromGitHub {
      owner = "affromero";
      repo = "gitpane";
      rev = "v0.9.1";
      fetchSubmodules = false;
      sha256 = "sha256-gly6+LGr1q0Tr9/rbDbbyuF0Pvh1KhHVQIywmUt5YLc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-gly6+LGr1q0Tr9_rbDbbyuF0Pvh1KhHVQIywmUt5YLc=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  hammerspoon = {
    pname = "hammerspoon";
    version = "1.1.1";
    src = fetchurl {
      url = "https://github.com/Hammerspoon/hammerspoon/releases/download/1.1.1/Hammerspoon-1.1.1.zip";
      sha256 = "sha256-EbsckPr1Qn83x71P5+q5d0rkPh1csCDFswiNrDKEnvo=";
    };
  };
  mermaid-rs-renderer = {
    pname = "mermaid-rs-renderer";
    version = "v0.3.1";
    src = fetchFromGitHub {
      owner = "1jehuang";
      repo = "mermaid-rs-renderer";
      rev = "v0.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-uekh1vJ19dAPP7+4PiqSlJizApZLpDhBWBoyN+fgS9s=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-uekh1vJ19dAPP7+4PiqSlJizApZLpDhBWBoyN+fgS9s=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  omniwm = {
    pname = "omniwm";
    version = "v0.5.8";
    src = fetchurl {
      url = "https://github.com/BarutSRB/OmniWM/releases/download/v0.5.8/OmniWM-v0.5.8.zip";
      sha256 = "sha256-5hM32qznSodBzAAaDIdLxF2V4CGcQV/T+uj1gz5nD5s=";
    };
  };
  paperwm-spoon = {
    pname = "paperwm-spoon";
    version = "34787bf38ce429a84f94ae00a73418e32cc1abb8";
    src = fetchFromGitHub {
      owner = "mogenson";
      repo = "PaperWM.spoon";
      rev = "34787bf38ce429a84f94ae00a73418e32cc1abb8";
      fetchSubmodules = false;
      sha256 = "sha256-hffz5Ae/INkYXRgZVX4FNejCbqC1l1aTigFRDFe8cYM=";
    };
    date = "2026-07-06";
  };
  powershell-beautifier = {
    pname = "powershell-beautifier";
    version = "V1.2.5";
    src = fetchFromGitHub {
      owner = "DTW-DanWard";
      repo = "PowerShell-Beautifier";
      rev = "V1.2.5";
      fetchSubmodules = false;
      sha256 = "sha256-N/Wz2TDgQFEW//QR5SwzFFJAiRx8+RoMS842m27mYjM=";
    };
  };
}
